package com.jyj.video.jyjplayer.db.dao;

import android.database.Cursor;
import android.database.sqlite.SQLiteStatement;

import com.jyj.video.jyjplayer.db.bean.Duration;

import org.greenrobot.greendao.AbstractDao;
import org.greenrobot.greendao.Property;
import org.greenrobot.greendao.database.Database;
import org.greenrobot.greendao.database.DatabaseStatement;
import org.greenrobot.greendao.internal.DaoConfig;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT.

/**
 * DAO for table "DURATION".
*/
public class DurationDao extends AbstractDao<Duration, String> {

    public static final String TABLENAME = "DURATION";

    /**
     * Properties of entity Duration.<br/>
     * Can be used for QueryBuilder and for referencing column names.
     */
    public static class Properties {
        public final static Property Path = new Property(0, String.class, "path", true, "PATH");
        public final static Property Duration = new Property(1, long.class, "duration", false, "DURATION");
    }


    public DurationDao(DaoConfig config) {
        super(config);
    }
    
    public DurationDao(DaoConfig config, DaoSession daoSession) {
        super(config, daoSession);
    }

    /** Creates the underlying database table. */
    public static void createTable(Database db, boolean ifNotExists) {
        String constraint = ifNotExists? "IF NOT EXISTS ": "";
        db.execSQL("CREATE TABLE " + constraint + "\"DURATION\" (" + //
                "\"PATH\" TEXT PRIMARY KEY NOT NULL UNIQUE ," + // 0: path
                "\"DURATION\" INTEGER NOT NULL );"); // 1: duration
    }

    /** Drops the underlying database table. */
    public static void dropTable(Database db, boolean ifExists) {
        String sql = "DROP TABLE " + (ifExists ? "IF EXISTS " : "") + "\"DURATION\"";
        db.execSQL(sql);
    }

    @Override
    protected final void bindValues(DatabaseStatement stmt, Duration entity) {
        stmt.clearBindings();
        stmt.bindString(1, entity.getPath());
        stmt.bindLong(2, entity.getDuration());
    }

    @Override
    protected final void bindValues(SQLiteStatement stmt, Duration entity) {
        stmt.clearBindings();
        stmt.bindString(1, entity.getPath());
        stmt.bindLong(2, entity.getDuration());
    }

    @Override
    public String readKey(Cursor cursor, int offset) {
        return cursor.getString(offset + 0);
    }    

    @Override
    public Duration readEntity(Cursor cursor, int offset) {
        Duration entity = new Duration( //
            cursor.getString(offset + 0), // path
            cursor.getLong(offset + 1) // duration
        );
        return entity;
    }
     
    @Override
    public void readEntity(Cursor cursor, Duration entity, int offset) {
        entity.setPath(cursor.getString(offset + 0));
        entity.setDuration(cursor.getLong(offset + 1));
     }
    
    @Override
    protected final String updateKeyAfterInsert(Duration entity, long rowId) {
        return entity.getPath();
    }
    
    @Override
    public String getKey(Duration entity) {
        if(entity != null) {
            return entity.getPath();
        } else {
            return null;
        }
    }

    @Override
    public boolean hasKey(Duration entity) {
        throw new UnsupportedOperationException("Unsupported for entities with a non-null key");
    }

    @Override
    protected final boolean isEntityUpdateable() {
        return true;
    }
    
}
