/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_gomo_quickvideo_filescan_JniUtils */

#ifndef _Included_com_gomo_quickvideo_filescan_JniUtils
#define _Included_com_gomo_quickvideo_filescan_JniUtils
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_gomo_quickvideo_filescan_JniUtils
 * Method:    getDocumentFiles
 * Signature: (Ljava/lang/String;)[Ljava/lang/String;
 */
JNIEXPORT void JNICALL Java_com_gomo_quickvideo_filescan_JniUtils_getDocumentFiles
  (JNIEnv *, jobject obj, jobjectArray str, jlong filter);

#ifdef __cplusplus
}
#endif
#endif
